from fastapi import FastAPI

app = FastAPI()


@app.get("/")
async def root():
    # GET A REQUEST, YOU HAVE THE FOLLOWING INPUTS
    # SOURCE IMAGE: SOURCE IMAGE
    # BOUNDING BOX: ON SOURCE IMAGE
    # QUERY
    
    # STEP ONE: RETRIEVE ALL RELEVANT ITEMS FROM THE QUERY
    
    
    # STEP TWO: ROUTE
    # ADD ONE ITEM TO A ROOM
    # ADD MULTIPLE ITEMS TO A ROOM

    # STEP THREE: CALL CONTROLNET API TO ADD THE IMAGE
    
    # STEP FOUR: EXTRACT THE BOUNDING BOXES FROM IMAGE


    # STEP FIVE: FILTER BOUNDING BOXES VIA OBJECT RECOGNITION
    
    
    # STEP SIX: CALL IMAGE COMPOSITION API
    
    
    
    return {"message": "Hello World"}